build:
    nodes:
        analysis: false
        tests:
            environment:
                php:
                    version: 7.3

filter:
    excluded_paths:
        - 'bin/*'
        - 'test/*'

coding_style:
    php: false
