build:
    environment:
        php:
            version: 7.3

tools:
    php_code_coverage:
        enabled: true
        filter:
            excluded_paths:
                - 'bin/*'
                - 'test/*'
    php_analyzer:
        enabled: false
