#!/usr/bin/env php
<?php

function autoload(): ?string
{
    foreach (['/../../autoload.php', '/../vendor/autoload.php', '/vendor/autoload.php'] as $usableFilePath) {
        $fullUsableFilePath = __DIR__ . $usableFilePath;
        if (file_exists($fullUsableFilePath)) {
            return $fullUsableFilePath;
        }
    }

    return null;
}

if (!($autoloadFilePath = autoload())) {
    fwrite(STDERR, 'You need to use composer to use generate-builder binary, learn more on https://getcomposer.org/');
    exit(1);
}

require $autoloadFilePath;

use Nati\BuilderGenerator\FileBuilderGenerator;

if (empty($argv[1])) {
    fwrite(STDERR, 'You must provide a filepath as first argument');
    exit(1);
}

$filepath = $argv[1];

try {
    FileBuilderGenerator::create()->generateFrom($filepath);
} catch (Throwable $e) {
    $msg = 'Error while generating builder';
    if ($more = $e->getMessage()) {
        $msg .= "\n" . $more;
    }
    fwrite(STDERR, $msg);
    exit(1);
}

fwrite(STDOUT, 'Builder class generated near ' . $filepath);
exit(0);
